[workspace]
resolver = "2"
members = [
    "aic_core",
    "aic_cli",
    "aic_app",
    "aic_agent",
    "aic_web"
]

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true
